#pragma once

enum Events
{
    EVENT_EXIT, 
    EVENT_ADD_PLAYER_CARD,
    EVENT_DEFINE_CARD,
    EVENT_MOVE_CARD,
    EVENT_SET_COLOR,
    EVENT_TURN_START,
    EVENT_SET_GEM,
    EVENT_END_GAME,
    EVENT_RESTART_GAME,
    EVENT_NEW_GAME,
};
